language: python

cache:
  directories:
  - $HOME/gnatsd

python:
  - 2.7

before_install:
  - bash ./script/install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH

install:
  - pip install -r requirements_dev.txt

script:
  - flake8 --exclude=benchmark,examples,tests
  - ./script/test.sh

notifications:
  email: false

sudo: required
dist: trusty
